### ISSUE TITLE
Default operation-key shall be removed from the configuration file for the generic services

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/MicroWaveDeviceGatekeeper#13]
Usually if a service don’t have security , then in the specification , we operation-key will be specified as “n.a”.
So , the Operation-key of the following services in the configuration file should be , “n.a”

mwdg-1-0-0-op-s-bs-000 , /v1/start-application-in-generic-representation
mwdg-1-0-0-op-s-bs-001 , /v1/inform-about-application
mwdg-1-0-0-op-s-bs-002, /v1/inform-about-application-in-generic-representation
mwdg-1-0-0-op-s-bs-003, /v1/inform-about-release-history
mwdg-1-0-0-op-s-bs-004, /v1/inform-about-release-history-in-generic-representation
mwdg-1-0-0-op-s-bs-005, /docs

> Note : having default operation-key will not create any problem. Raised this issue as we follow this as a standard in other application.

**Comment by openBackhaul** [comment]
Changed as proposed.
