### ISSUE TITLE
How to update the client information of NotificationProxy and OpenDayLight controller

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/MicroWaveDeviceGatekeeper#14]
MWDG interacts with NotificationProxy and OpenDayLight controller.
We don’t have an API in the IndividualService to update the tcp-clients of the NotificationProxy and the OpenDayLight controller.
So, following is our understanding , 
**To update the tcp-client :** 
1.	During the deployment of the application , using the fake-ip-address script the tcp-client information of the NotificationProxy and OpenDayLight controller will be updated.
2.	During the runtime , if we wish to configure , then the tcp-client OAM services shall be utilized.

**To update the ODL credentials :**
1.	During the deployment,  Base64encode of ODL credential shall be included into the applicationData/encrypted-odl-key.json

Kindly correct us if our understanding is wrong. Thanks.

**Comment by openBackhaul** [comment]
I confirm your understanding in all described aspects.
No correction required.

**Comment by PrathibaJee** [comment]
Thank you for the confirmation. 
Closing this issue as there is no further clarification required,
