### ISSUE TITLE
Not subscribed to the create, delete controller event from NotificationProxy

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/MicroWaveDeviceGatekeeper#15]
From MWDG , we are subscribing to the /v1/notify-controller-attribute-value-changes subscription of NotificationProxy.
And we are not subscribing to the /v1/notify-controller-object-creations , /v1/notify-controller-object-deletions events.
Kindly please let us know is it fine.

**Comment by openBackhaul** [comment]
Yes, we are not subscribing at /v1/notify-controller-object-creations and /v1/notify-controller-object-deletions.
Please, close the issue after reading, if no further need for clarification.

**Comment by PrathibaJee** [comment]
Thank you for the confirmation.
Closing this issue as there is no further clarification required,
