### ISSUE TITLE
Clarification regarding the implementation for ApplicationPattern/BasicServices

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/MicroWaveDeviceGatekeeper#16]
Both OAS and CONFIG file of MicroWaveDeviceGatekeeper version 1.0.0_spec points to the 2.0.2 version of TinyApplicationController.
Also , the included applicationPattern OAS includes the fix proposed for the milestone AP v2.0.2_spec.

Kindly please let us know your views regarding the following , 

- As of now , a complete implementation of version 2.0.2 of ApplicationPattern is not available.
- But we have a preliminary version of 2.0.2 ApplicationPattern Implementation which will cover around 50% of the version AP2.0.2.

Kindly please let us know whether we shall proceed with the preliminary version of 2.0.2 ApplicationPattern Implementation.
(Above proposal is based on the assumption that AP v2.0.2_spec will be released in the upcoming months and MWDG is targeted to work with TAC 2.0.2)

**Comment by openBackhaul** [comment]
My intention is to finalize and publish specification of AP v2.0.2 as soon as possible.
New applications shall be based on AP v2.0.2 .
Please, close after reading, if no further need for clarification.

**Comment by PrathibaJee** [comment]
Thank you for the confirmation. 
We will use the npm package that has the initial implementation of 2.0.2 . 
Once the final 2.0.2_impl is ready , we will update the npm package to latest.
Closing this issue as there is no further clarification required,
