### ISSUE TITLE
POST operation that performs RPCs should point to the /rests/operations and not the /rests/data

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/MicroWaveDeviceGatekeeper#17]
For the POST operation /core-model-1-4:network-control-domain=live/control-construct={mountName}/mac-fd-1-0:provide-learned-mac-addresses that performs RPCs , the prefix should point to the operations as below , 

http://\<CONTROLLERIP\>:\<port\>/**`rests/operations/network-topology:network-topology/topology=topology-netconf`**/node={MountName}/yang-ext:mount/mac-fd-1-0:provide-learned-mac-addresses

So proposing the following, 

**Config file :**

1. A new string profile mwdg-1-0-0-string-p-002 that holds the path to execute the rpcs needs to be included, 
```
rests/operations/network-topology:network-topology/topology=topology-netconf
```
2. The following operation-name in the mwdg-1-0-0-op-c-is-odl-4-0-2-270 shall be changed from , 
/{controllerInternalPathToMountPoint}/node={mountName}/yang-ext:mount/mac-fd-1-0:provide-learned-mac-addresses
to 
/{new String profile name that points to the operations}/node={mountName}/yang-ext:mount/mac-fd-1-0:provide-learned-mac-addresses

**OAS :**
1. In the callback , PostToLiveRpcForProvidingLearnedMacAdressesCausesInitiatingRpcExecutionOnDevice 
controllerInternalPathToMountPoint shall be changed to {new String profile name that points to the operations}
2. Schema description shall point to the new string-profile uuid mwdg-1-0-0-string-p-002
3. Example shall be changed from 
'rests/data/network-topology:network-topology/topology=topology-netconf' 
to 
'rests/operations/network-topology:network-topology/topology=topology-netconf'

**Comment by openBackhaul** [comment]
Changed as proposed.
Many thanks for describing the need for change in deep detail.
