### ISSUE TITLE
Discrepancies between the uuid and path of the request-body attribute of the callback ControllerAttributeValueChangeNotifications 

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/MicroWaveDeviceGatekeeper#19]
1. In the callback ControllerAttributeValueChangeNotifications, in the description of the attributes subscribing-application-name and subscribing-application-release, the uuid points to the **http-server** , whereas the subsequence path leads to a **http-client-interface-configuration** , 
      - The **subscribing-application-name** path shall be changed from 
            _/core-model-1-4:control-construct/logical-termination-point=mwdg-1-0-0-http-s-000/layer-protocol=0/**`http-client-interface-1-0:http-client-interface-pac/http-client-interface-configuration/application-name`**_
            to 
            _/core-model-1-4:control-construct/logical-termination-point=mwdg-1-0-0-http-s-000/layer-protocol=0/**`http-server-interface-1-0:http-server-interface-pac/http-server-interface-capability/application-name`**_
      
      - The **subscribing-application-release** path shall be changed from 
            _/core-model-1-4:control-construct/logical-termination-point=mwdg-1-0-0-http-s-000/layer-protocol=0/**`http-client-interface-1-0:http-client-interface-pac/http-client-interface-configuration/release-number`**_
            to 
            _/core-model-1-4:control-construct/logical-termination-point=mwdg-1-0-0-http-s-000/layer-protocol=0/**`http-server-interface-1-0:http-server-interface-pac/http-server-interface-capability/release-number`**_
---------
2. In the description of the attributes subscribing-application-protocol, subscribing-application-address/ip-address, subscribing-application-address/domain-name and subscribing-application-port, the uuid points to the tcp-server , whereas the subsequence path leads to a tcp-client-interface-configuration , 

      - The **subscribing-application-protocol** path shall be changed from 
            _/core-model-1-4:control-construct/logical-termination-point=mwdg-1-0-0-tcp-s-000/layer-protocol=0/**`tcp-client-interface-1-0:tcp-client-interface-pac/tcp-client-interface-configuration/remote-protocol`**_
            to 
            _/core-model-1-4:control-construct/logical-termination-point=mwdg-1-0-0-tcp-s-000/layer-protocol=0/**`tcp-server-interface-1-0:tcp-server-interface-pac/tcp-server-interface-configuration/local-protocol`**_
      
      - The **subscribing-application-address/ip-address** path shall be changed from 
            _/core-model-1-4:control-construct/logical-termination-point=mwdg-1-0-0-tcp-s-000/layer-protocol=0/**`tcp-client-interface-1-0:tcp-client-interface-pac/tcp-client-interface-configuration/remote-address/ip-address/ipv-4-address`**_
            to 
            _/core-model-1-4:control-construct/logical-termination-point=mwdg-1-0-0-tcp-s-000/layer-protocol=0/**`tcp-server-interface-1-0:tcp-server-interface-pac/tcp-server-interface-configuration/local-address/ipv-4-address`**_
      
      - The **subscribing-application-address/domain-name** path shall be changed from 
            _/core-model-1-4:control-construct/logical-termination-point=mwdg-1-0-0-tcp-s-000/layer-protocol=0/**`tcp-client-interface-1-0:tcp-client-interface-pac/tcp-client-interface-configuration/remote-address/domain-name`**_
            to
            _/core-model-1-4:control-construct/logical-termination-point=mwdg-1-0-0-tcp-s-000/layer-protocol=0/**`tcp-server-interface-1-0:tcp-server-interface-pac/tcp-server-interface-configuration/local-address/domain-name`**_
      
      -The **subscribing-application-port** path shall be changed from 
            _/core-model-1-4:control-construct/logical-termination-point=mwdg-1-0-0-tcp-s-000/layer-protocol=0/**`tcp-client-interface-1-0:tcp-client-interface-pac/tcp-client-interface-configuration/remote-port`**_ 
            to
            _/core-model-1-4:control-construct/logical-termination-point=mwdg-1-0-0-tcp-s-000/layer-protocol=0/**`tcp-server-interface-1-0:tcp-server-interface-pac/tcp-server-interface-configuration/local-port`**_
---------
3. In the description of the attribute notifications-receiving-operation, the uuid points to an operation-server , whereas the subsequence path leads to a operation-client-interface-configuration , 
      - The **notifications-receiving-operation** path shall be changed from 
            _/core-model-1-4:control-construct/logical-termination-point=mwdg-1-0-0-op-s-is-000/layer-protocol=0/**`operation-client-interface-1-0:operation-client-interface-pac/operation-client-interface-configuration/operation-name`**_ 
            to
            _/core-model-1-4:control-construct/logical-termination-point=mwdg-1-0-0-op-s-is-000/layer-protocol=0/**`operation-server-interface-1-0:operation-server-interface-pac/operation-server-interface-configuration/operation-name`**_

**Comment by openBackhaul** [comment]
Changed as proposed.
Please excuse the mistake.
Thanks for indicating and describing in deep detail.
