### ISSUE TITLE
Uuids mentioned in the description of the attribute “subscription“ in the callback PromptForBequeathingDataCausesUnsubscribingFromControllerNotificationsAtNP shall be removed

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/MicroWaveDeviceGatekeeper#20]
As per the description in the callback of /v1/bequeath-your-data-and-die , PromptForBequeathingDataCausesUnsubscribingFromControllerNotificationsAtNP we have to initiate end-subscription for 5 subscription. 
But as per the embedding process,  MWDI subscribes only for one notification in the NotificationProxy (i.e) /v1/notify-controller-attribute-value-changes. 
So , during the bequeathing process , only a single end-subscription will be sufficient to end the subscription of the controller-value-change notification. 

The following text shall be removed from the description of the attribute “subscription“ as the mentioned uuids are not part of the MWDG application , 

```	
and
from [/core-model-1-4:control-construct/logical-termination-point=mwdg-1-0-0-op-c-is-np-1-0-1-010/layer-protocol=0/operation-client-interface-1-0:operation-client-interface-pac/operation-client-interface-configuration/operation-name]
and
from [/core-model-1-4:control-construct/logical-termination-point=mwdg-1-0-0-op-c-is-np-1-0-1-011/layer-protocol=0/operation-client-interface-1-0:operation-client-interface-pac/operation-client-interface-configuration/operation-name]
and
from [/core-model-1-4:control-construct/logical-termination-point=mwdg-1-0-0-op-c-is-np-1-0-1-012/layer-protocol=0/operation-client-interface-1-0:operation-client-interface-pac/operation-client-interface-configuration/operation-name]
and
from [/core-model-1-4:control-construct/logical-termination-point=mwdg-1-0-0-op-c-is-np-1-0-1-013/layer-protocol=0/operation-client-interface-1-0:operation-client-interface-pac/operation-client-interface-configuration/operation-name]
in five separate, sequential requests.'
```

Also the above mentioned uuids mwdg-1-0-0-op-c-is-np-1-0-1-010, mwdg-1-0-0-op-c-is-np-1-0-1-011, mwdg-1-0-0-op-c-is-np-1-0-1-012, mwdg-1-0-0-op-c-is-np-1-0-1-013 are not part of the MWDG’s configuration file

**Comment by openBackhaul** [comment]
Changed as proposed.
Many thanks for indicating.
