### ISSUE TITLE
An empty request-body needs to be included in the RPC mac-fd-1-0:provide-learned-mac-addresses

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/MicroWaveDeviceGatekeeper#22]
As of now , an empty json request-body needs to be sent to process the RPC mac-fd-1-0:provide-learned-mac-addresses.

![image](https://github.com/openBackhaul/MicroWaveDeviceGatekeeper/assets/62344562/9869188b-11ab-4d18-8c50-44b872ede59b)

If we don't provide an empty request-body , then we will receive 500 internal server from the controller , 

![image](https://github.com/openBackhaul/MicroWaveDeviceGatekeeper/assets/62344562/d044384a-cdea-4bf7-819f-914918e5beec)

> Note : Including an empty json requestbody in a RPC call is generic and not specific to this RPC alone.     

**Proposal :** 
In the OAS , Could you please include an empty json request-body for the callback PostToLiveRpcForProvidingLearnedMacAdressesCausesInitiatingRpcExecutionOnDevice.

**Comment by openBackhaul** [comment]
Changed as proposed.
Many thanks for analyzing the subject and guiding to the solution.
