### ISSUE TITLE
Request to update "string-profile-1-0:integer-profile-pac" to the  "string-profile-1-0:string-profile-pac" in config.json as per schema 

### ISSUE THREAD

**Issue by ManasaBM1** [openBackhaul/MicroWaveDeviceGatekeeper#38]
**Problem Statement :**
As per the schema of string profile in MicroWaveDeviceGatekeeper+profiles.yaml should contain property as  "string-profile-1-0:string-profile-pac"

But In config.json the string profile is present as mentioned below where it contains property name as "string-profile-1-0:integer-profile-pac"

```
{
          "uuid": "mwdg-1-0-0-string-p-000",
          "profile-name": "string-profile-1-0:PROFILE_NAME_TYPE_STRING_PROFILE",
          "string-profile-1-0:integer-profile-pac": {
            "string-profile-capability": {
              "string-name": "controllerInternalPathToMountPoint"
            },
            "string-profile-configuration": {
              "string-value": "rests/data/network-topology:network-topology/topology=topology-netconf"
            }
      }
 }
```

**Solution :**

In config.json file , can we please change the  "string-profile-1-0:integer-profile-pac" to  "string-profile-1-0:string-profile-pac" for the string-profile's
as per the schema.

**Comment by openBackhaul** [comment]
Changed as proposed.
Thanks for indicating.
