### ISSUE TITLE
Clarification on required functionalities

### ISSUE THREAD

**Issue by nardecchia-siae** [openBackhaul/MicroWaveDeviceGatekeeper#7]
We need confirmation of our understanding of functionalities required in first version
Specifically, clarification about how to manage connected device list (only via notification?)

**Comment by openBackhaul** [comment]
While embedding the list of devices in connected state shall be loaded from the Controller.  
After that 
- the list shall be updated based on ControllerAttributeChangedNotifications sent by the NotificationProxy
- and at the end of every deviceListSyncPeriod the list of devices in connected state shall again be loaded from the Controller.

The list shall not be stored in file of database.
