### ISSUE TITLE
Request to update the string-profile-configuration property name to "string-value" in config.json as per schema

### ISSUE THREAD

**Issue by ManasaBM1** [openBackhaul/MicroWaveDeviceGatekeeper#8]
**Problem Statement :** 
As per the schema of string profile in MicroWaveDeviceGatekeeper+profiles.yaml the string-profile-configuration should contain property name as "string-value"
 
But In config.json the string profile is present as mentioned below where string-profile-configuration contains property name as "string-name"

```
{
          "uuid": "mwdg-1-0-0-string-p-000",
          "profile-name": "string-profile-1-0:PROFILE_NAME_TYPE_STRING_PROFILE",
          "string-profile-1-0:integer-profile-pac": {
            "string-profile-capability": {
              "string-name": "controllerInternalPathToMountPoint"
            },
            "string-profile-configuration": {
              "string-name": "rests/data/network-topology:network-topology/topology=topology-netconf"
            }
        }
   }
 
```
**Solution :**
 
In config.json file , can we please change the string-profile-configuration property name to **"string-value**" instead of **"string-name"** for the string-profile's
as per the schema.

**Comment by openBackhaul** [comment]
Changed as proposed.
