### ISSUE TITLE
Request to add op-c "mwdg-1-0-0-op-c-is-odl-4-0-2-299" to the client-ltp list of http-c "mwdg-1-0-0-http-c-odl-4-0-2-000" in config.json

### ISSUE THREAD

**Issue by ManasaBM1** [openBackhaul/MicroWaveDeviceGatekeeper#9]
**Problem Description :**
 
In config.json , as per the server-ltp list of operation-client "mwdg-1-0-0-op-c-is-odl-4-0-2-299" that is as mentioned below , the operation-client is instance http-client "mwdg-1-0-0-http-c-odl-4-0-2-000" which belongs to 
ODL application.
 
```
{
        "uuid": "mwdg-1-0-0-op-c-is-odl-4-0-2-299",
        "ltp-direction": "core-model-1-4:TERMINATION_DIRECTION_SINK",
        "client-ltp": [
        ],
        "server-ltp": [
          "mwdg-1-0-0-http-c-odl-4-0-2-000"
        ],
        "layer-protocol": [
          {
            "local-id": "0",
            "layer-protocol-name": "operation-client-interface-1-0:LAYER_PROTOCOL_NAME_TYPE_OPERATION_LAYER",
            "operation-client-interface-1-0:operation-client-interface-pac": {
              "operation-client-interface-configuration": {
                "operation-name": "/{controllerInternalPathToMountPoint}/node={mountName}/yang-ext:mount/core-model-1-4:control-construct/logical-termination-point={uuid}/layer-protocol={localId}/pure-ethernet-structure-2-0:pure-ethernet-structure-pac/pure-ethernet-structure-configuration/performance-monitoring-is-on",
                "operation-key": "n.a."
 }
```
 
But operation-client "mwdg-1-0-0-op-c-is-odl-4-0-2-299" is missing from the client-ltp list of http-c "mwdg-1-0-0-http-c-odl-4-0-2-000" that belongs to ODL application.
 
**Solution :**
 
Request to add operation-client "mwdg-1-0-0-op-c-is-odl-4-0-2-299" to the client-ltp list of http-client "mwdg-1-0-0-http-c-odl-4-0-2-000" in config.json.

**Comment by openBackhaul** [comment]
Changed as proposed. Thanks for indicating.
